"""Translate VM commands into Hack assembly code"""

class CodeWriter:

    def __init__(self, out_file):
        self.root = out_file[:-4]
        self.out_file = open(out_file, "w")
        self.next_label = 0

    def write_arithmetic(self, command):
        """Write the assembly code that is the translation of the given arithmetic command"""
        trans = ""
        trans += "// " + command + "\n"
        if command == "add":
            trans += "@SP\n" #Push first value of stack on D 
            trans += "AM=M-1\n"
            trans += "D=M\n"
            trans += "@SP\n"
            trans += "AM=M-1\n"
            trans += "M=D+M\n"
            trans += "@SP\n"
            trans += "M=M+1\n"
            trans += "\n"
        elif command == "sub":
            trans += "@SP\n"
            trans += "AM=M-1\n"
            trans += "D=M\n"
            trans += "@SP\n"
            trans += "AM=M-1\n"
            trans += "M=M-D\n"
            trans += "@SP\n"
            trans += "M=M+1\n"
            trans += "\n"
        elif command == "neg":
            trans += "@SP\n"
            trans += "A=M-1\n"
            trans += "M=-M\n"
            trans += "\n"
        elif command == "eq":
            label = str(self.next_label)
            self.next_label += 1 
            trans += "@SP\n"
            trans += "AM=M-1\n"
            trans += "D=M\n"
            trans += "@SP\n"
            trans += "A=M-1\n"
            trans += "D=M-D\n"
            trans += "M=-1\n"
            trans += f"@eqTrue{label}\n"
            trans += "D;JEQ\n"
            trans += "@SP\n"
            trans += "A=M-1\n"
            trans += "M=0\n"
            trans += f"(eqTrue{label})\n"      
            trans += "\n"   
        elif command == "gt":
            label = str(self.next_label)
            self.next_label += 1 
            trans += "@SP\n"
            trans += "AM=M-1\n"
            trans += "D=M\n"
            trans += "@SP\n"
            trans += "A=M-1\n"
            trans += "D=M-D\n"
            trans += "M=-1\n"
            trans += f"@gtTrue{label}\n"
            trans += "D;JGT\n"
            trans += "@SP\n"
            trans += "A=M-1\n"
            trans += "M=0\n"
            trans += f"(gtTrue{label})\n"
            trans += "\n"
        elif command == "lt":
            label = str(self.next_label)
            self.next_label += 1 
            trans += "@SP\n"
            trans += "AM=M-1\n"
            trans += "D=M\n"
            trans += "@SP\n"
            trans += "A=M-1\n"
            trans += "D=M-D\n"
            trans += "M=-1\n"
            trans += f"@ltTrue{label}\n"
            trans += "D;JLT\n"
            trans += "@SP\n"
            trans += "A=M-1\n"
            trans += "M=0\n"
            trans += f"(ltTrue{label})\n"
            trans += "\n"
        elif command == "and":
            trans += "@SP\n"
            trans += "AM=M-1\n"
            trans += "D=M\n"
            trans += "@SP\n"
            trans += "A=M-1\n"
            trans += "M=D&M\n"
            trans += "\n"
        elif command == "or":
            trans += "@SP\n"
            trans += "AM=M-1\n"
            trans += "D=M\n"
            trans += "@SP\n"
            trans += "A=M-1\n"
            trans += "M=D|M\n"
            trans += "\n"
        elif command == "not":
            trans += "@SP\n"
            trans += "A=M-1\n"
            trans += "M=!M\n"
            trans += "\n"
        else:
            trans = command + " not implemented yet\n"
        self.out_file.write(trans)


    def write_push_pop(self, command, segment, index):
        """Write the assembly code that is the translation of the given command (C_PUSH or C_POP)"""
        trans = ""
        if command == "push":
            trans += "// push " + segment + " " + index + "\n"
            if segment == "constant":
                trans += "@" + index + "\n" 
                trans += "D=A\n"
                trans += "@SP\n"
                trans += "A=M\n"
                trans += "M=D\n"
                trans += "@SP\n"
                trans += "M=M+1\n"
                trans += "\n"
            elif segment == "local":
                trans += "@" + index + "\n"
                trans += "D=A\n"
                trans += "@LCL\n"
                trans += "A=M+D\n"
                trans += "D=M\n"
                trans += "@SP\n"
                trans += "A=M\n"
                trans += "M=D\n"
                trans += "@SP\n"
                trans += "M=M+1\n"
                trans += "\n"
            elif segment == "this":
                trans += "@" + index + "\n"
                trans += "D=A\n"
                trans += "@THIS\n"
                trans += "A=M+D\n"
                trans += "D=M\n"
                trans += "@SP\n"
                trans += "A=M\n"
                trans += "M=D\n"
                trans += "@SP\n"
                trans += "M=M+1\n"
                trans += "\n"
            elif segment == "that":
                trans += "@" + index + "\n"
                trans += "D=A\n"
                trans += "@THAT\n"
                trans += "A=M+D\n"
                trans += "D=M\n"
                trans += "@SP\n"
                trans += "A=M\n"
                trans += "M=D\n"
                trans += "@SP\n"
                trans += "M=M+1\n"
                trans += "\n"
            elif segment == "argument":
                trans += "@" + index + "\n"
                trans += "D=A\n"
                trans += "@ARG\n"
                trans += "A=M+D\n"
                trans += "D=M\n"
                trans += "@SP\n"
                trans += "A=M\n"
                trans += "M=D\n"
                trans += "@SP\n"
                trans += "M=M+1\n"
                trans += "\n"
            elif segment == "temp":
                trans += "@" + index + "\n"
                trans += "D=A\n"
                trans += "@R5\n"
                trans += "A=A+D\n"
                trans += "D=M\n"
                trans += "@SP\n"
                trans += "A=M\n"
                trans += "M=D\n"
                trans += "@SP\n"
                trans += "M=M+1\n"
                trans += "\n"
            elif segment == "pointer":
                trans += "@" + index + "\n"
                trans += "D=A\n"
                trans += "@R3\n"
                trans += "A=A+D\n"
                trans += "D=M\n"
                trans += "@SP\n"
                trans += "A=M\n"
                trans += "M=D\n"
                trans += "@SP\n"
                trans += "M=M+1\n"
                trans += "\n"
            elif segment == "static":
                trans += "@" + self.root + "." + index + "\n"
                trans += "D=M\n"
                trans += "@SP\n"
                trans += "A=M\n"
                trans += "M=D\n"
                trans += "@SP\n"
                trans += "M=M+1\n"
                trans += "\n"
        elif command == "pop":
            trans += "// pop " + segment + " " + index + "\n"
            if segment == "argument":
                trans += "@" + index + "\n"
                trans += "D=A\n"
                trans += "@ARG\n"
                trans += "D=M+D\n"
                trans += "@R13\n"
                trans += "M=D\n"
                trans += "@SP\n"
                trans += "AM=M-1\n"
                trans += "D=M\n"
                trans += "@R13\n"
                trans += "A=M\n"
                trans += "M=D\n"
                trans += "\n"
            elif segment == "local":
                trans += "@" + index + "\n"
                trans += "D=A\n"
                trans += "@LCL\n"
                trans += "D=M+D\n"
                trans += "@R13\n"
                trans += "M=D\n"
                trans += "@SP\n"
                trans += "AM=M-1\n"
                trans += "D=M\n"
                trans += "@R13\n"
                trans += "A=M\n"
                trans += "M=D\n"
                trans += "\n"
            elif segment == "this":
                trans += "@" + index + "\n"
                trans += "D=A\n"
                trans += "@THIS\n"
                trans += "D=M+D\n"
                trans += "@R13\n"
                trans += "M=D\n"
                trans += "@SP\n"
                trans += "AM=M-1\n"
                trans += "D=M\n"
                trans += "@R13\n"
                trans += "A=M\n"
                trans += "M=D\n"
                trans += "\n"
            elif segment == "that":
                trans += "@" + index + "\n"
                trans += "D=A\n"
                trans += "@THAT\n"
                trans += "D=M+D\n"
                trans += "@R13\n"
                trans += "M=D\n"
                trans += "@SP\n"
                trans += "AM=M-1\n"
                trans += "D=M\n"
                trans += "@R13\n"
                trans += "A=M\n"
                trans += "M=D\n"
                trans += "\n"
            elif segment == "temp":
                trans += "@" + index + "\n"
                trans += "D=A\n"
                trans += "@5\n"
                trans += "D=D+A\n"
                trans += "@R13\n"
                trans += "M=D\n"
                trans += "@SP\n"
                trans += "AM=M-1\n"
                trans += "D=M\n"
                trans += "@R13\n"
                trans += "A=M\n"
                trans += "M=D\n"
                trans += "\n"
            elif segment == "static":
                trans += "@SP\n"
                trans += "AM=M-1\n"
                trans += "D=M\n"
                trans += "@" + self.root + "." + index + "\n"
                trans += "M=D\n"
                trans += "\n"
            elif segment == "pointer":
                trans += "@SP\n"
                trans += "AM=M-1\n"
                trans += "D=M\n"
                if index == "0":
                    trans += "@THIS\n"
                    trans += "M=D\n"
                elif index == "1":
                    trans += "@THAT\n"
                    trans += "M=D\n"
                trans += "\n"
        self.out_file.write(trans)

    def write_error(self):
        self.out_file.write("There is no command like this.")